### ISSUE TITLE
Program will not run

### ISSUE THREAD

**Issue by lostinhiding** [janbodnar/Java-Pacman-Game#1]
Pacman.java:16: error: cannot find symbol

/Java-Pacman-Game-master/src/com/zetcode$ java Pacman.java
Pacman.java:15: error: cannot find symbol
        add(new Board());
                ^
  symbol:   class Board
  location: class Pacman
1 error
error: compilation failed

**Comment by janbodnar** [comment]
This is beginner issue. The program is OK.
